#!/bin/bash

if [ $# -ne 2 ]
then 
    echo "Runs the specified advent of code puzzle.
    
Usage: run [PUZZLE DIRECTORY] [PART NUMBER] (e.g. run day01 1)"
elif [ ! -d "$1" ]
then
    echo "Could not find directory '$1'!"
elif [ $2 == "1" ] || [ $2 == "2" ]
then
    pushd $1 > /dev/null
    echo "Running $1 part $2... the output:"
    time go run main.go $2
    popd > /dev/null
else
    echo "Part number must be 1 or 2!"
fi
